CREATE TABLE IF NOT EXISTS USERS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER_PROFILE(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USER_ID INTEGER NOT NULL,
	GROSS_SALARY_MONTHLY REAL DEFAULT 0,
	NET_SALARY_MONTHLY REAL DEFAULT 0,
	ESTIMATED_EXPENSES_MONTHLY REAL DEFAULT 0,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WALLETS(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USER_ID INTEGER NOT NULL,
	NAME TEXT NOT NULL,
	CURRENCY TEXT NOT NULL DEFAULT 'PLN',
	INITIAL_BALANCE REAL NOT NULL DEFAULT 0,
	CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CATEGORIES(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	WALLET_ID INTEGER NOT NULL,
	PARENT_ID INTEGER,
	NAME TEXT NOT NULL,
	OPERATION_TYPE TEXT NOT NULL DEFAULT 'Expense',
	COLOR TEXT DEFAULT '#0085FC',
	IS_PROTECTED BOOLEAN NOT NULL DEFAULT 0,
	FOREIGN KEY (WALLET_ID) REFERENCES WALLETS(ID) ON DELETE CASCADE,
	FOREIGN KEY (PARENT_ID) REFERENCES CATEGORIES(ID) ON DELETE CASCADE,
	UNIQUE(WALLET_ID, PARENT_ID, NAME)
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	WALLET_ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER NOT NULL,
	TITLE TEXT NOT NULL,
	DESCRIPTION TEXT,
	DATE TEXT NOT NULL,
	OPERATION_TYPE TEXT NOT NULL,
	AMOUNT REAL NOT NULL,
	MERCHANT TEXT,
	RECURRING_ID INTEGER,
	CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (WALLET_ID) REFERENCES WALLETS(ID) ON DELETE CASCADE,
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID) ON DELETE RESTRICT,
	FOREIGN KEY (RECURRING_ID) REFERENCES RECURRING_TRANSACTIONS(ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS RECURRING_TRANSACTIONS(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	WALLET_ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER NOT NULL,
	TITLE TEXT NOT NULL,
	DESCRIPTION TEXT,
	OPERATION_TYPE TEXT NOT NULL,
	AMOUNT REAL NOT NULL,
	MERCHANT TEXT,
    RECURRENCE_INTERVAL TEXT NOT NULL, 
    START_DATE TEXT NOT NULL,
    END_DATE TEXT,
    NEXT_DUE_DATE TEXT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT 1,
	CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (WALLET_ID) REFERENCES WALLETS(ID) ON DELETE CASCADE,
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID) ON DELETE CASCADE
);
